---
# Deploy certs to different system
#
- name: "Deploy new certs"
  hosts: all
  gather_facts: true

  tasks:
    - name: "Install certs on unifi cloudkeys"
      include_role:
        name: unifi
      when: "'unifi' in group_names"

    # - name: Install certs on esxi hosts
    #   include_role:
    #     name: esxi
    #   when: "'esx' in hostvars[inventory_hostname].group_names"

    - name: "Install certs on synology hosts"
      include_role:
        name: synology
      when: "'synology' in group_names"

    - name: "Install certs on proxmox hosts"
      include_role:
        name: proxmox
      when: "'proxmox' in group_names"
