---
# deployment playbook for letsencrypt certificates, created for example with certbot.
# I'm using nginx proxy manager to manage certificates, which creates ECC certs
# and by that, forced me to rewrite most of the script I had been using with RSA certs.
# the roles included can distribute and install certs on following system (version tested with)
# - unifi cloudkey gen2 (tested on 4.4.3, 5.0.16)
# - proxmox (9.1.1)
# - synology nas (dsm 7.2.2)
#
- name: Deploy new certs
  hosts: all
  gather_facts: true

  tasks:
    - name: Install certs on unifi
      include_role:
        name: unifi
      when: "'unifi' in group_names"

    # - name: Install certs on esxi hosts
    #   include_role:
    #     name: esxi
    #   when: "'esx' in hostvars[inventory_hostname].group_names"

    - name: Install certs on synology hosts
      include_role:
        name: synology
      when: "'synology' in group_names"

    - name: Install certs on proxmox hosts
      include_role:
        name: proxmox
      when: "'proxmox' in group_names"
