---
# this works but will most likely need some work
# in case other services uses the same certs.
# see it as a work in progress, contributions and suggestions are welcome

- name: "Get default cert"
  become: yes
  slurp:
    src: "{{ synology_default_cert_file }}"
  register: synology_cert_id_file

- name: "Set default cert fact"
  set_fact:
    synology_cert_id: "{{ synology_cert_id_file['content'] | b64decode | trim }}"

- name: "Get cert info"
  become: yes
  slurp:
    src: "{{ synology_cert_info_file }}"
  register: sybology_cert_info_file

- name: "Set cert info fact"
  set_fact:
    synology_cert_info: "{{ sybology_cert_info_file['content'] | b64decode | trim }}"

- name: "Build list of services and packages"
  set_fact:
    synology_pkg_services: "{{ synology_cert_info[synology_cert_id].services | selectattr('isPkg','equalto',true) | list }}"
    synology_nonpkg_services: "{{ synology_cert_info[synology_cert_id].services | selectattr('isPkg','equalto',false) | list }}"
    
- name: "Capture the login users home directory"
  set_fact:
    original_user_home: "{{ ansible_env.HOME }}"

- name: "Upload certs to temporary directory"
  ansible.builtin.copy:
    src: "{{ cert_source_path }}/"
    dest: "{{ original_user_home }}/{{ cert_dest_tmpdir }}"
    directory_mode: '0700'
    mode: '0600'

- name: "Copy certs to default cert folder"
  become: yes
  ansible.builtin.copy:
    src: "{{ original_user_home }}/{{ cert_dest_tmpdir }}/"
    dest: "{{ synology_cert_path }}/{{ synology_cert_id }}"
    remote_src: true
    mode: '0400'

- name: "Find directories containing existing certificates"
  become: yes
  ansible.builtin.find:
    paths: "{{ synology_package_cert_path }}"
    recurse: yes
    patterns: "cert.pem"
    file_type: file
  register: found_certs

- name: "Copy new certs to discovered package folders"
  become: yes
  ansible.builtin.copy:
    src: "{{ original_user_home }}/{{ cert_dest_tmpdir }}/"
    dest: "{{ item.path | dirname }}/"
    remote_src: true
    mode: '0400'
    directory_mode: '0755'
  loop: "{{ found_certs.files }}"
  loop_control:
    label: "{{ item.path | dirname }}"
  notify: "Restart Synology Packages"

- name: "Ensure cert directories got correct permissions"
  become: yes
  ansible.builtin.file:
    path: "{{ item.path | dirname }}"
    state: directory
    mode: '0755'
  loop: "{{ found_certs.files }}"

- name: "Sync Handlers"
  meta: flush_handlers

- name: "Regenerate certs for difference services" # only needed if using as reverse proxy?
  become: yes
  ansible.builtin.command: "/usr/syno/bin/synow3tool --gen-all"

# this will copy certs to /usr/syno/etc/certificate/system/default as well
- name: "Restart nginx"
  become: yes
  ansible.builtin.command: "/usr/syno/bin/synosystemctl restart nginx"

- name: "Remove temporary cert folder"
  ansible.builtin.file:
    path: "{{ original_user_home }}/{{ cert_dest_tmpdir }}"
    state: absent